In [9]:
import pandas as pd 
import numpy as np

In [10]:
df = pd.read_csv('matches - matches.csv')

# Fetching rows and coloumn

In [11]:
df[['season','city']]

     season       city
0      2017  Hyderabad
1      2017       Pune
2      2017     Rajkot
3      2017     Indore
4      2017  Bangalore
..      ...        ...
631    2016     Raipur
632    2016  Bangalore
633    2016      Delhi
634    2016      Delhi
635    2016  Bangalore

[636 rows x 2 columns]

In [12]:
df.iloc[0]

id                                                         1
season                                                  2017
city                                               Hyderabad
date                                              2017-04-05
team1                                    Sunrisers Hyderabad
team2                            Royal Challengers Bangalore
toss_winner                      Royal Challengers Bangalore
toss_decision                                          field
result                                                normal
dl_applied                                                 0
winner                                   Sunrisers Hyderabad
win_by_runs                                               35
win_by_wickets                                             0
player_of_match                                 Yuvraj Singh
venue              Rajiv Gandhi International Stadium, Uppal
umpire1                                          AY Dandekar
umpire2                                             NJ Llong
umpire3                                                  NaN
Name: 0, dtype: object

In [13]:
df.iloc[0:3]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN

In [14]:
df.iloc[[1,5,18,22]]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
5,6,2017,Hyderabad,2017-04-09,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong,NaN
18,19,2017,Hyderabad,2017-04-17,Sunrisers Hyderabad,Kings XI Punjab,Kings XI Punjab,field,normal,0,Sunrisers Hyderabad,5,0,B Kumar,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,A Deshmukh,NaN
22,23,2017,Kolkata,2017-04-21,Kolkata Knight Riders,Gujarat Lions,Gujarat Lions,field,normal,0,Gujarat Lions,0,4,SK Raina,Eden Gardens,CB Gaffaney,Nitin Menon,NaN

In [15]:
df.iloc[:,4:8] 
#column slicing using iloc 
#iloc slicing is similar to numpys row,column slicing

,team1,team2,toss_winner,toss_decision
0,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field
1,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field
2,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field
3,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field
4,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat
...,...,...,...,...
631,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field
632,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field
633,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field
634,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field
635,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat

In [16]:
df.iloc[:,[4,5,6,7]] #slicing using fancy indexing

,team1,team2,toss_winner,toss_decision
0,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field
1,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field
2,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field
3,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field
4,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat
...,...,...,...,...
631,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field
632,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field
633,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field
634,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field
635,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat

(636, 18)